function getData(){
    return data = [
        "./img/1.webp", "小白",
        "./img/2.webp", "小黑",
        "./img/3.webp", "小明", 
        "./img/4.webp", "晓得", 
        "./img/5.webp", "小李",
        "./img/6.webp", "小胡", 
        "./img/7.webp", "小黄", 
        "./img/8.webp", "小智",
        "./img/9.webp", "小新",
        "./img/10.webp", "汪仔",
        "./img/1.webp", "小白",
        "./img/2.webp", "小黑",
        "./img/3.webp", "小明", 
        "./img/4.webp", "晓得", 
        "./img/5.webp", "小李",
        "./img/6.webp", "小胡", 
        "./img/7.webp", "小黄", 
        "./img/8.webp", "小智",
        "./img/9.webp", "小新",
        "./img/10.webp", "汪仔",
        "./img/1.webp", "小白",
        "./img/2.webp", "小黑",
        "./img/3.webp", "小明", 
        "./img/4.webp", "晓得", 
        "./img/5.webp", "小李",
        "./img/6.webp", "小胡", 
        "./img/7.webp", "小黄", 
        "./img/8.webp", "小智",
        "./img/9.webp", "小新",
        "./img/10.webp", "汪仔",
    ];
}